### ISSUE TITLE
[Android] "File is too large" issue when loading CHD file.

### ISSUE THREAD

**Issue by retro-wertz** [libretro/Genesis-Plus-GX#111]
Cannot run CHD files under linux. core is updated, core info and retroarch.

```
I/RetroArch( 6052): Mega CD (PAL) BRAM is located at: /storage/sdcard0/RetroArch/saves/scd_E.brm
I/RetroArch( 6052): Sega CD (NTSC-U) BRAM is located at: /storage/sdcard0/RetroArch/saves/scd_U.brm
I/RetroArch( 6052): Mega CD (NTSC-J) BRAM is located at: /storage/sdcard0/RetroArch/saves/scd_J.brm
I/RetroArch( 6052): Sega/Mega CD RAM CART is located at: /storage/sdcard0/RetroArch/saves/cart.brm
I/RetroArch( 6052): File is too large.
E/RetroArch( 6052): Failed to load content.
I/RetroArch( 6052): Environ SET_PIXEL_FORMAT: RGB565.


```

https://github.com/libretro/Genesis-Plus-GX/blob/master/libretro/libretro.c#L226

the same chd works fine in linux.

**Comment by ekeeke** [comment]
CHD support needs to be enabled in Android.mk, same as CPU overclock support and Sprite Limits removal

**Comment by blackman91** [comment]
Can the libretro guys enable those features for Android please?

**Comment by blackman91** [comment]
Any news on if the overclock option is coming to the Android version?

**Comment by hizzlekizzle** [comment]
@blackman91 Someone has to get into the JNI makefile and do it. I'm not familiar enough with them to do it myself, unfortunately.

**Comment by blackman91** [comment]
I just saw that the overclock option was added to the Android version, pretty nice job as always guys you rock!

**Comment by ekeeke** [comment]
To add CHD support in JNI makefile, you should only have to :

1) add following defines to LOCAL_CFLAGS
" -DUSE_LIBCHDR -DPACKAGE_VERSION=\"1.3.2\" -DFLAC_API_EXPORTS -DFLAC__HAS_OGG=0 -DHAVE_LROUND -DHAVE_STDINT_H -D_7ZIP_ST -DHAVE_SYS_PARAM_H"

2) add following directories to LOCAL_C_INCLUDES:
"$(CHDLIBDIR)/src $(CHDLIBDIR)/deps/libFLAC/include $(CHDLIBDIR)/deps/lzma $(CHDLIBDIR)/deps/zlib"

**Comment by retro-wertz** [comment]
Thanks @ekeeke @hizzlekizzle . genesis_plus_gx now works in Android(arm7). Just one more issue though. there is a redifined warning for PAGE_MASK which is tied to mapper_t5740_w(), might need checking.

```
/home/buildbot/buildbot/android/libretro-genesis_plus_gx/libretro/jni/../../core/cart_hw/eeprom_spi.c:43:0: warning: "PAGE_MASK" redefined
 #define PAGE_MASK 0x7f
 ^
In file included from /home/buildbot/tools/android/android-ndk-r13b/platforms/android-9/arch-arm/usr/include/limits.h:109:0,
                 from /home/buildbot/tools/android/android-ndk-r13b/platforms/android-9/arch-arm/usr/include/math.h:22,
                 from /home/buildbot/buildbot/android/libretro-genesis_plus_gx/libretro/jni/../../core/shared.h:7,
                 from /home/buildbot/buildbot/android/libretro-genesis_plus_gx/libretro/jni/../../core/cart_hw/eeprom_spi.c:39:
/home/buildbot/tools/android/android-ndk-r13b/platforms/android-9/arch-arm/usr/include/asm/page.h:17:0: note: this is the location of the previous definition
 #define PAGE_MASK (~(PAGE_SIZE-1))
 ^
```

if this will not cause issue, then its safe to close this thread. again Thanks.

**Comment by ekeeke** [comment]
As long as macro is defined in .c file after includes, this won't cause any issue since local definition will overlap any SDK library macro definition with the same name and this will only apply to the associated object file, which is what is intended.

**Comment by ekeeke** [comment]
As long as macro is defined in .c file after includes, this won't cause any issue since local definition will overlap any SDK library macro definition with the same name and this will only apply to the associated object file, which is what is intended.

**Comment by retro-wertz** [comment]
sounds good. thanks.
