### ISSUE TITLE
(Suggestion) Remove nuked option for low-powered devices

### ISSUE THREAD

**Issue by nikkoman** [libretro/Genesis-Plus-GX#119]
I believe that the new accurate sound engines are a pointless menu option for low-powered devices such as the Raspberry Pi.

Even on my overclocked RPi 3, non-mame makes emulation extremely slow, which makes sense given the accuracy. Mame is the only option for sound for that core (and such devices).

**Comment by ekeeke** [comment]
This can be done easily by setting -DHAVE_YM3438_CORE in Makefile.libretro only for platforms that can handle it but this require testing of this option with all available platform before deciding it's a pointless option or not.
