### ISSUE TITLE
genesis_plus_gx_libretro_ps3 

### ISSUE THREAD

**Issue by DEX357** [libretro/Genesis-Plus-GX#129]
genesis_plus_gx_libretro_ps3 freez in black screen after launch game, after that the console must be hard turned off, I test all other cores and only this permanently freezes consoles that you can not do anything but turn it off. All Sega consol MG/GG/MD. I always installs a new night update when it comes out.

**Comment by DEX357** [comment]
I found a problem, I used the old core, the Polish translation apparently something that causes the Sega core to hang

**Comment by ekeeke** [comment]
Please close this issue if this is fixed, let's try not cluttering the issue page of this repository.
