### ISSUE TITLE
Core crashes on Raspberry Pi 3 with MS Light Phaser control and Crosshairs option enabled

### ISSUE THREAD

**Issue by msheehan79** [libretro/Genesis-Plus-GX#131]
As of RetroArch v1.6.9, the core will crash on the Raspberry Pi 3 if Player 1 controller is set to "MS Light Phaser" and the core option to draw crosshairs is enabled. 

This crash did not occur with RetroArch v1.6.7, but was replicated on v1.6.9 and v1.7.0. 

Also it does not occur with the same versions of RetroArch on Windows 10 x64 so it does appear the crash is platform-specific.

Also potentially useful info - if the MS Light Phaser is enabled first and the crosshairs core option is enabled later it does not crash. But if the crosshairs are enabled first before selecting the controller the crash occurs consistently. It seems to be related to the initial pointer coordinates being 0, 0 when the controller is first selected. 

I found that putting a check in the draw_cursor function to return without processing if both x and y are set to 0 avoids the crash, although this feels like a band-aid solution rather than addressing the underlying reason for the crash, I'm quite sure there is a better solution out there than this.

```C
static void draw_cursor(int16_t x, int16_t y, uint16_t color)
{
   if((x == 0) && (y == 0))
      return;
   uint16_t *ptr = (uint16_t *)bitmap.data + ((bitmap.viewport.y + y) * bitmap.width) + x + bitmap.viewport.x;
   ptr[-3*bitmap.width] = ptr[-bitmap.width] = ptr[bitmap.width] = ptr[3*bitmap.width] = ptr[-3] = ptr[-1] = ptr[1] = ptr[3] = color;
   ptr[-2*bitmap.width] = ptr[2*bitmap.width] = ptr[-2] = ptr[2] = ptr[0] = 0xffff;
}

**Comment by ekeeke** [comment]
Indeed, that code is not safe for (x,y) values close to the edge of the screen since it will try to write pixel data outside of the framebuffer reserved area. Something must have changed in RETRO_POINTER drivers that made it always return such values in later versions but theoretically crash could occur in older versions as well when trying to point the edge of the screen.

**Comment by msheehan79** [comment]
Thanks for the advice on this. I took a crack at rewriting the cursor function to be aware of the boundaries of the viewport and it will adjust the starting/ending points for the crosshairs now so it will only draw the visible portion of the crosshair when on the edges of the screen. 

As murphy's law would have it, the Dolphinbar I got to use light gun games failed only a few days after I got it so I've got a new one on the way. But everything seems fine on Windows x64, and basic testing (i.e. does it crash upon initial loading) on the RPI3 seems good so once I get a proper light gun setup to test this more I will submit a PR for this.

Of course, if you have any suggestions or improvements on the below comments are welcome. 

```C
static void draw_cursor(int16_t x, int16_t y, uint16_t color)
{
   uint16_t *ptr = (uint16_t *)bitmap.data + ((bitmap.viewport.y + y) * bitmap.width) + x + bitmap.viewport.x;
   static uint16_t min_width, min_height, max_width, max_height;
   static int16_t x_start, x_end, y_start, y_end, i;
   static uint8_t crosshair_size = 3;

   min_width = crosshair_size;
   min_height = crosshair_size;
   max_width = bitmap.viewport.w - crosshair_size;
   max_height = bitmap.viewport.h - crosshair_size;

   /* Determine if the crosshair is in the viewport bounds */
   /* otherwise adjust the start or end points of the crosshair so only the visible area is drawn */
   if (x >= min_width)
      x_start = crosshair_size * -1;
   else
      x_start = x * -1;

   if (x <= max_width)
      x_end = crosshair_size;
   else
      x_end = bitmap.viewport.w - x;

   if (y >= min_height)
      y_start = crosshair_size * -1;
   else
      y_start = y * -1;

   if (y <= max_height)
      y_end = crosshair_size;
   else
      y_end = bitmap.viewport.h - y;

   /* Draw the crosshairs */
   for (i = x_start; i <= x_end; i++)
   {
      ptr[i] = (i % 2 == 0 ? 0xffff : color);
   }

   for (i = y_start; i <= y_end; i++)
   {
      ptr[i * bitmap.width] = (i % 2 == 0 ? 0xffff : color);
   }
}

**Comment by ekeeke** [comment]
I pretty much had something similar in mind  but which allows drawing pixels in border area if they are rendered to framebuffer (when bitmap.viewport.x != 0 or bitmap.viewport.y != 0). 

Something like this:

```
static void draw_cursor(int16_t x, int16_t y, uint16_t color)
{
   int i;

   /* crosshair center position */ 
   uint16_t *ptr = (uint16_t *)bitmap.data + ((bitmap.viewport.y + y) * bitmap.width) + x + bitmap.viewport.x;

  /* default crosshair dimension */
  int x_start = x - 3;
  int x_end  = x + 3;
  int y_start = y - 3;
  int y_end = y + 3;

  /* framebuffer limits */
  if (x_start < -bitmap.viewport.x) x_start = -bitmap.viewport.x;
  if (x_end >= (bitmap.viewport.w + bitmap.viewport.x) x_end= bitmap.viewport.w + bitmap.viewport.x - 1;
  if (y_start < -bitmap.viewport.y) y_start = -bitmap.viewport.y;
  if (y_end >= (bitmap.viewport.h + bitmap.viewport.y) y_end = bitmap.viewport.h + bitmap.viewport.y - 1;

 /* draw crosshair  */
  for (i = (x_tart - x); i <= (x_end - x), i++)
     ptr[i] = (i & 1) ? color : 0xffff;
  for (i = (y_tart - y); i <= (y_end -y), i++)
     ptr[i * bitmap.width] = (i & 1) ? color : 0xffff;
  }

```

**Comment by msheehan79** [comment]
No worries! I dropped your code into my file here and compiled it on Windows and RPI3 after fixing a couple small typos. 

While I'm sure you don't need validation that the code works, just figured I'd pass along that it does resolve the crash on the Pi for me.

I'll leave the pull request to you, but glad to see the approach taken was similar to what I came up with if only for my own experience.

**Comment by illando** [comment]
Hi guys,
I'm not a developer and not an exptert about releses.
I just want to ask you if this bug fix you are talking about in this thread is already implemented in the official release.
Any chance I can upload the genesis-plus-GX core on Retropie and see this bug fixed?
Thanks.

**Comment by msheehan79** [comment]
It's not fixed as of the latest build. 

@ekeeke I deferred on submitting a fix on the assumption that as primary maintainer of this core you'd want to handle the fix - but if you are busy or are otherwise OK with it I'm happy to submit a PR to fix this so we can close this issue.

I'm not sure on github if there is a way to defer credit to you or anything but if that is possible I can do so since I'd use your version of the fix.

**Comment by ekeeke** [comment]
Yes, I don't really have the time to test and submit a pull request so feel free to do it if that solution worked for you, I don't really care about being credited.
null

**Comment by illando** [comment]
@msheehan79 Thanks in advance!
Talking about the Dolphin Bar, if it's any consolation, it stopped working mine too after 3 weeks.
They do not seem very solid! I also asked for a replacement.

**Comment by illando** [comment]
@msheehan79 Tested on my Rpi3 and it works!
Thanks again!

**Comment by ekeeke** [comment]
@msheehan79 : please close this issue if this is fixed.
