### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/Genesis-Plus-GX#17]
Last commit i have been able to build is https://github.com/libretro/Genesis-Plus-GX/commit/8d5ce59878f1bd87d1424ea73f5ad5d00eea49cc

Current fail with this error : 
core/mem68k.c: In function ‘ctrl_io_write_byte’:
core/mem68k.c:649:39: error: ‘m68ki_cpu_core’ has no member named ‘cpu_stopped’
             unsigned int status = s68k.cpu_stopped;
                                       ^
core/mem68k.c:680:21: error: ‘m68ki_cpu_core’ has no member named ‘cpu_stopped’
             if (s68k.cpu_stopped != status)
                     ^
core/mem68k.c:685:23: error: ‘m68ki_cpu_core’ has no member named ‘cpu_stopped’
               if (s68k.cpu_stopped & STOP_LEVEL_HALT)
                       ^
core/mem68k.c:685:38: error: ‘STOP_LEVEL_HALT’ undeclared (first use in this function)
               if (s68k.cpu_stopped & STOP_LEVEL_HALT)
                                      ^
core/mem68k.c:685:38: note: each undeclared identifier is reported only once for each function it appears in
core/mem68k.c:700:95: error: ‘m68k_unused_w_8’ undeclared (first use in this function)
                 m68k.memory_map[base + 0x02].write8  = m68k.memory_map[base + 0x03].write8  = m68k_unused_w_8;
                                                                                               ^
core/mem68k.c:701:95: error: ‘m68k_unused_w_16’ undeclared (first use in this function)
                 m68k.memory_map[base + 0x02].write16 = m68k.memory_map[base + 0x03].write16 = m68k_unused_w_16;
                                                                                               ^
core/mem68k.c: In function ‘ctrl_io_write_word’:
core/mem68k.c:875:39: error: ‘m68ki_cpu_core’ has no member named ‘cpu_stopped’
             unsigned int status = s68k.cpu_stopped;
                                       ^
core/mem68k.c:906:21: error: ‘m68ki_cpu_core’ has no member named ‘cpu_stopped’
             if (s68k.cpu_stopped != status)
                     ^
core/mem68k.c:911:23: error: ‘m68ki_cpu_core’ has no member named ‘cpu_stopped’
               if (s68k.cpu_stopped & STOP_LEVEL_HALT)
                       ^
core/mem68k.c:911:38: error: ‘STOP_LEVEL_HALT’ undeclared (first use in this function)
               if (s68k.cpu_stopped & STOP_LEVEL_HALT)
                                      ^
core/mem68k.c:926:95: error: ‘m68k_unused_w_8’ undeclared (first use in this function)
                 m68k.memory_map[base + 0x02].write8  = m68k.memory_map[base + 0x03].write8  = m68k_unused_w_8;
                                                                                               ^
core/mem68k.c:927:95: error: ‘m68k_unused_w_16’ undeclared (first use in this function)
                 m68k.memory_map[base + 0x02].write16 = m68k.memory_map[base + 0x03].write16 = m68k_unused_w_16;

Btw i'm using gcc-4.8.3

**Comment by twinaphex** [comment]
Upstream issue.

**Comment by sergiobenrocha2** [comment]
It's already fixed in upstream.

**Comment by ekeeke** [comment]
I cannot close fixed issue in this repository so please someone do it.
