### ISSUE TITLE
Lock-on with sk.bin not working ?

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/Genesis-Plus-GX#18]
I'm sure my sk.bin is OK (at least that's the sk.bin to use with genplus 1.7), but activating sonic & knuckles lock-on in core option won't do anything when i load any of the sonic roms. Retroarch output this : 

RetroArch: rarch_log_libretro: [libretro INFO] :: INFORMATION - Loading 2097152 bytes ...
RetroArch [ERROR] :: rarch_log_libretro :: [libretro ERROR] :: File is too large.

**Comment by sergiobenrocha2** [comment]
Weird, it's working here.

some sk.bin info:

md5sum: 4ea493ea4e9f6c9ebfccbdb15110367e
size: 2 MiB (2097152 bytes)

And you need sk2chip.bin too, if it's missing lock-on will not work:

md5sum: b4e76e416b887f4e7413ba76fa735f16
size: 256 KiB (262144 bytes)

**Comment by barbudreadmon** [comment]
With good md5sum, it's finally working. Thank you !
