### ISSUE TITLE
[Sega CD] Extra memory not exposed

### ISSUE THREAD

**Issue by Jamiras** [libretro/Genesis-Plus-GX#191]
We've recently enabled RetroAchievements for Sega CD using the Genesis Plus GX core, and one of our developers noted that the memory he needed was not available in the editor.

Using BizHawk, he found the data he was looking for in the "CD PRG RAM". Which appears to be 512KB of additional memory not currently exposed by the core. This is apparently additional memory specific to the Sega CD peripheral:

From https://en.wikibooks.org/wiki/Genesis_Programming#MegaCD_Changes:
> "Program RAM" is $80000 bytes in size, but is only accessible by the Genesis 68K in banks of size $20000, and only when the MegaCD 68K is in "BUSREQ" (stopped).

For achievement development, we'd prefer this entire block be accessible, rather than rely on banking semantics. Using the `libretro` interface, `RETRO_MEMORY_SYSTEM_RAM` only exposes the 64KB associated to the "68000 RAM". `RETRO_MEMORY_SAVE_RAM` doesn't return anything, and `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` does not appear to be called. These are the three things we use for interacting with the core's memory.

I'm not sure how extended memory fits into the `libretro` interface, but I expect that exposing it through `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` would be the preferred solution.

**Comment by Jamiras** [comment]
I'm not sure if this hasn't made it to the nightly build of the core yet, or if it's just not working correctly, but the RETRO_ENVIRONMENT_SET_MEMORY_MAPS callback isn't being invoked when loading a Sega CD title.

Additionally, I also expect the 68000 RAM to be provided in the memory map (at $FF0000). Once a core exposes a memory map, it's used for all memory accessing done by the achievement processing code. The CD RAM doesn't replace the 68000 RAM, it's in addition to.

I do recommend not returning a memory map for non-CD games at this time, as the achievement processing code will have to be updated to specify the base address to look for when mapping the 68000 RAM.

**Comment by negativeExponent** [comment]
- i believe the memmap should already be available in latest buildbot, at least for linux:
![gpgx](https://user-images.githubusercontent.com/54053706/71771273-688c6f80-2f73-11ea-812a-b02fb168bd54.png)

- the mapping should only take effect when a CD game is loaded as stated on the PR. non-CD games will take the normal get_memory_data/size callback for memory access
- ill update the map to add 68k ram at $FF0000

**Comment by Jamiras** [comment]
Confirmed the behavior. Thanks.
