### ISSUE TITLE
Emulation locks up when resetting Sega/Mega CD games

### ISSUE THREAD

**Issue by bleakassassin** [libretro/Genesis-Plus-GX#21]
Anytime I reset the system while playing a CD game, the system boots back to the BIOS screen. However, emulation locks up and no logos can be seen on the main screen.

If this is expected behavior for an actual Sega/Mega CD system, feel free to disregard this. I know that the RESET button is used to open the drive of a Model 1 system, but it shouldn't cause it to lock up like this. Even if the button functionality was implemented, pressing START should close the system anyways.

**Comment by ekeeke** [comment]
Should be fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/4a41e0cca7bfc043fd8fd929b2344e6add2a0f10

**Comment by bleakassassin** [comment]
Yeah, that did fix it. Thanks!

I probably should have closed this issue a long time ago. At the same time, though, reading it now does make me think about the soft reset function. I don't know if RetroArch did soft resetting back in mid-2015, but it seems to have it now. For other cores, at least, not this one.
