### ISSUE TITLE
Possible to update to the latest git?

### ISSUE THREAD

**Issue by telanus** [libretro/Genesis-Plus-GX#217]
Since the latest git suppor Mega SD MD+, will the core be updated to allow that functionality in retroarch?

**Comment by RokkumanX** [comment]
This is recently freshly compiled (24/10) from ekeeke/Genesis-Plus-GX and should include what you want.

[genesis_plus_gx_libretro.zip](https://github.com/libretro/Genesis-Plus-GX/files/5457383/genesis_plus_gx_libretro.zip)
