### ISSUE TITLE
[Feature Request] Add an option to remove left side border ( Sega Master System)

### ISSUE THREAD

**Issue by frafes** [libretro/Genesis-Plus-GX#218]
I was wondering if is possible add an option to remove the left border in some Sega Master System games. Recently that [option was added in smsplus-gx core](https://github.com/libretro/smsplus-gx/commit/22ce804bc1cf6094ee217a787317f01d16b7f8a2) and it is very nice. 

In the picture below is possible compare the game "Gangster Town" with and without the left border.

**Genesis-Plus-GX core:** the left border is part of the title screen and the gameplay.
![g_ts](https://user-images.githubusercontent.com/72279502/95007412-12be2400-05e6-11eb-9792-103c5b7d1b21.jpg) 
![g_gp](https://user-images.githubusercontent.com/72279502/95007423-3c774b00-05e6-11eb-9827-0a4425c25d8b.jpg)

**smsplus-gx core (option to remover left border on):**  the border stills present in the title screen and it is removed only during the gameplay.
![s_ts](https://user-images.githubusercontent.com/72279502/95007431-4ef18480-05e6-11eb-988a-d593b814ca95.jpg)
![s_gp](https://user-images.githubusercontent.com/72279502/95007433-587aec80-05e6-11eb-8061-cfb96f0a2492.jpg)

**Comment by JLiszt** [comment]
I second this request... it would be great if this were added.

**Comment by ds22x** [comment]
Third this request because, while it is more accurate, having that border displayed just doesn't look good or right.

**Comment by ds22x** [comment]
Thought I might as well give it a shot, and I got it somewhat working as a core option:
https://github.com/ds22x/Genesis-Plus-GX

It cuts off 8 pixels on both left and right side of the screen, and while it works for the Master System, and doesn't apply to the Mega Drive, it for some reason breaks the aspect ratio of the Game Gear when the viewpoint is updated.

**Comment by frafes** [comment]
It doesn’t work right with some games like Phantasy Star menu screen and California Games:

![ss](https://user-images.githubusercontent.com/72279502/106846833-69b73100-668c-11eb-94b3-794d87d0e9b9.png)

**Comment by ds22x** [comment]
Because those games use static screens (for which the left border can be used), rather than scrolling screens.
In those cases it's better to leave the option off.

**Comment by ds22x** [comment]
I'll close this for the time being, as the request has been technically fulfilled, pending a more dynamic way of hiding the left border can be achieved.

**Comment by ds22x** [comment]
A more dynamic way of hiding the left border has been achieved as of https://github.com/libretro/Genesis-Plus-GX/commit/1fa86c141d8a8a7a0a4530a224d07612ad7b87a4

**Comment by frafes** [comment]
Thanks @ds22x, this is great.

I would like to make a suggestion:
After testing the option to hide the left border in the game "california games", I noticed that the left border in the "half pipe event" is missing, so I made a change to the code:
I changed these lines in the file libretro.c:

>    if (!do_skip)
	   	if ((config.left_border == 1) && (bitmap.viewport.x == 0) && ((system_hw == SYSTEM_MARKIII) || (system_hw & SYSTEM_SMS) || (system_hw == SYSTEM_PBC)))
		    video_cb(bitmap.data + 16, vwidth - 8, vheight, 720 * 2);
			else if ((config.left_border == 2) && (bitmap.viewport.x == 0) && ((system_hw == SYSTEM_MARKIII) || (system_hw & SYSTEM_SMS) || (system_hw == SYSTEM_PBC)))
			video_cb(bitmap.data + 16, vwidth - 16, vheight, 720 * 2);
			else
			video_cb(bitmap.data, vwidth, vheight, 720 * 2); 
   else<

For:

>    if (!do_skip)
	   	if (**(reg[0] & 0x20) &&** (config.left_border == 1) && (bitmap.viewport.x == 0) && ((system_hw == SYSTEM_MARKIII) || (system_hw & SYSTEM_SMS) || (system_hw == SYSTEM_PBC)))
		    video_cb(bitmap.data + 16, vwidth - 8, vheight, 720 * 2);
			else if (**(reg[0] & 0x20) &&** (config.left_border == 2) && (bitmap.viewport.x == 0) && ((system_hw == SYSTEM_MARKIII) || (system_hw & SYSTEM_SMS) || (system_hw == SYSTEM_PBC)))
			video_cb(bitmap.data + 16, vwidth - 16, vheight, 720 * 2);
			else
			video_cb(bitmap.data, vwidth, vheight, 720 * 2); 
   else<



Now the "half pipe event" has the background complete and the borders are hidled only in the others events (surfing, skating...). It's working also in the title screen of "Gangster Town" game.
Works for both "hide only left border" " hide right and left borders" options.

I'm not a programmer so dont't know if I did the right thing. 
Could you make a test with these changes, please?
Thanks

**Comment by ds22x** [comment]
Tested it and it seems to work fine with the twenty or so games I threw at it.

**Comment by Sanaki** [comment]
Hmm... could you check again? I just tested it on a whim on Linux and it's not working here. Even the left and right border option isn't.

**Comment by ds22x** [comment]
Thanks for the heads-up.
Seems that adding a `bitmap.viewport.x = 0` check made it not work when hiding the overscan borders.
