### ISSUE TITLE
Possible license violation:

### ISSUE THREAD

**Issue by Hydro5** [libretro/Genesis-Plus-GX#22]
https://itunes.apple.com/app/id982939500

This guy is selling Snes9x, GenplusGX and other emulators plus some indie ("homebrew") games on the Apple store. It is said to be RetroArch iOS with Snes9x, GenplusGX and other cores. I believe Snes9x and Genplus GX have non-commercial clauses preventing their use in commercial products correct?

The Content Dispute Form is here:

http://www.apple.com/legal/internet-services/itunes/appstorenotices/
Also posted: 
https://github.com/snes9xgit/snes9x/issues/73
https://github.com/libretro/snes9x/issues/12

**Comment by hizzlekizzle** [comment]
Yes, that's definitely correct. I'm surprised he made it through the App Store approval process with emulator names right in the description...

**Comment by Hydro5** [comment]
He uses the term "indie games" for the games, and calls the emulators "engines". He intentionally tried to hide the nature of the product.

**Comment by ekeeke** [comment]
It has been reported to apple and the guy removed his app from apple appstore, this can be closed.
Thanks.
