### ISSUE TITLE
Retroarch Linux Version - MSU-MD doesn't work

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/Genesis-Plus-GX#234]
I'm using Retroarch on Linux, intalled from flathub.

Version: 1.9.0
Core Version: v1.7.4 e4151a2

Problem: On linux, the msu-md rom doesn't work. Only the fx effects play.

MD5SUM rom patched: ea4c1771f94abc0d7b4769d7e9d72081

**Comment by hizzlekizzle** [comment]
I don't think the libretro buildbot builds have MSU-MD support. I think you'd have to get a build of eke's upstream.

**Comment by ZacharyFoxx** [comment]
Hmmmm... ok...

**Comment by ToniBC** [comment]
The ekeeke versions do have support for MSU-MD, but the ones created by the Buildbot have not applied the latest changes or have not yet implemented or approved the latest changes on this.

You have to look and update that, hopefully you will see.

I tried it with the ekeeke versions in Retroarch and they reproduce without problems, but only for Windows they are available.
