### ISSUE TITLE
Lightgun Crosshair Shows Even When Set to Off

### ISSUE THREAD

**Issue by Awakened0** [libretro/Genesis-Plus-GX#24]
I loaded up Snatcher in the latest nightly and the crosshair doesn't go away even when set to off in the core options.

**Comment by ekeeke** [comment]
Indeed, there is a typo in libretro.C regarding the two last core options ("Gun cursor" and "Mouse Y-Axis") which makes them always enabled regardless of user setting.

Please open an issue here: https://github.com/ekeeke/Genesis-Plus-GX/issues

**Comment by ekeeke** [comment]
Indeed, there is a typo in libretro.c regarding the two last core options ("Gun cursor" and "Mouse Y-Axis") which makes them always enabled regardless of user setting.

Please close this one and reopen it here: https://github.com/ekeeke/Genesis-Plus-GX/issues
