### ISSUE TITLE
Skeleton Krew (USA) - 6 Button Mapping Issue

### ISSUE THREAD

**Issue by ghost** [libretro/Genesis-Plus-GX#242]
Skeleton Krew (USA) has a mapping issue where the X,Y,Z buttons are ignored, this game is 6 button compatible.
Select Option, then scroll to Kontrol and press Right multiple times should bring up multiple variants of ways to map the X,Y,Z buttons, which don't show up as if the 6 button controller wasn't detected.

RetroArch 1.9.1
Genesis Plus GX v1.7.4 a110a05

Android
Windows 10

**Comment by bslenul** [comment]
`Quick Menu > Controls > Port 1 Controls > Device Type`, change to "MD Joypad 6 Button" and it should work fine:

![image](https://user-images.githubusercontent.com/33353403/115108740-68e72900-9f72-11eb-83e7-7779dd5260ee.png)

**Comment by ner00** [comment]
I think this issue should be closed, I also confirm that manually toggling the controller type to `MD Joypad 6 Button` works.

**Comment by ekeeke** [comment]
6B control pad is automatically emulated when input is set to "MD Joypad Auyo" only if the loaded ROM header indicates the game supports 6B controller so likeky this game forgot to indicate 6B support in its ROM header.

So yes, this is neither a core emulation or libretro issue.
