### ISSUE TITLE
Darius has strange sound?

### ISSUE THREAD

**Issue by ketburai** [libretro/Genesis-Plus-GX#246]
Well, it seems I had posted this in the wrong place; I had originally posted it [here](https://github.com/ekeeke/Genesis-Plus-GX/issues/367). This issue seems to occur with Genesis Plus GX in Retroarch or BizHawk, but not regular Genesis Plus GX on GC/Wii.

Noticed something odd about this particular title. Some instruments/sound effects seem to be playing at a higher pitch than is expected. I personally am experiencing this in BizHawk, and I believe [this](https://www.youtube.com/watch?v=o1cEVHBdW4U) is a video of someone using Retroarch getting the same result. I also noticed that the sounds in question are playing slightly faster than they should as well.

I have no idea what this might sound like on a regular Mega Drive, but it's definitely not how the Mega Drive Mini sounds, as shown [here](https://www.youtube.com/watch?v=YLDy_QpPxks) and [here](https://www.youtube.com/watch?v=QQh2armyVuw). The Mega Drive Mini also sounds more like the arcade original, which it's supposed to be a semi-port of ("semi" as in obviously you can't feasibly do three screens on a Mega Drive). Additionally, the sound seems to match the Mega Drive Mini when I attempt to play the game in Fusion. I figured it'd be the other way around, honestly.

I decided to have a look at other emulators...
- Gens _does_ have the higher pitch.
- Regen also _does_ have the higher pitch.
- BlastEm does _not_ have the higher pitch.
- Exodus also does _not_ have the higher pitch.
- Last but not least, MAME _does_ have the higher pitch.

Of course, I have each emulator set to an NTSC device, and since I play a lot of Japanese games each emulator was set to default to Japan NTSC whenever possible (Darius is set to be multi-region and I don't think there are any region differences, not even text? Darius has pretty sparse endings). In fact, setting any emulator to use PAL doesn't seem to do anything different in this specific case.

I am assuming this is some extremely specific quirk that the Darius port has. To be honest, to my untrained ears, it sounds as if the lower pitch is something the game is _applying_ to what is "normally" higher pitched sounds/instruments, but I truly have no idea.

I also have not been able to see the version that was released in Darius Cozmic Revelation (which I think is a Japan-exclusive Amazon preorder bonus unfortunately), so I have no idea what's going on there either.

edit: I have no idea what's going on anymore, sorry.

**Comment by Augusto7743** [comment]
Test comparing both MAME YM2612 and Nuked YM2612

**Comment by ekeeke** [comment]
This issue was actually experienced by the reporter on bizhawk only and he assumed that the same issue occured also in retroarch  because of some youtube video that does not even indicate which emulator was used (could be Gens or Regen who knows ?). I could not reproduce this issue in Retroarch (see original issue report linked above) so I think this can safely be closed.
