### ISSUE TITLE
Genesis Plus GX loading Double Dragon 2 much slow than real console

### ISSUE THREAD

**Issue by Augusto7743** [libretro/Genesis-Plus-GX#262]
Core using default CPU 100 % speed.
Try load Double Dragon 2.
The game is extremely slow if comparing with console. Music run in good tempo , but controls and gameplay are much slow.
If you change CPU clock to 125 or 150 % not has slowdowns , but will break some others games.
Retroarch and genesis gx core previous versions before 06-21 not happen that issue.

**Comment by ekeeke** [comment]
Tested with latest core and did not notice any particularely slow gameplay. The game has some slowdowns occuring from time to time but I verified these happened on real hardware as well, cf https://github.com/ekeeke/Genesis-Plus-GX/issues/356.

Anyway,  there is nothing in core changes from the last 6 months that affect CPU or VDP emulation so this issue most likely started occurring after some frontend or libretro core settings changes on your side. Things like automatic frameskipping or runahead might have an effect on this game for example.

**Comment by Augusto7743** [comment]
Yes the game have slowdowns in console, but in Retroarch previous version had slowdown.
In previous version had terrible slowdown.
Current version not has the issue.

**Comment by ekeeke** [comment]
>Current version not has the issue

If the reported issue does not occur anymore after a retroarch update, it means it was not a core issue and you should close it to avoid unecessary lookup/analysis from core devs... or whoever is interested in fixing pending issues.
