### ISSUE TITLE
Ghostbuster graphics issues

### ISSUE THREAD

**Issue by Augusto7743** [libretro/Genesis-Plus-GX#267]
When player character is hitted by enemy shot happen a player character flickering.
Current genesis core not is rendering the flickering effect, but the player character sprite not is rendered in screen.

When the sub boss is defeated player character will hunt him using a beam weapon. beam weapon does a laser rendered effect.
Current genesis core not is rendering beam weapon laser effect.

Only start first stage going to right. Is easy to test it.

**Comment by ekeeke** [comment]
I quickly tested this game and confirmed the flickering effect is there when being it so this must be an issue on your end (retroarch or libretro core settings).

This kind of effect is usually done by making sprites disappearing/appearing in consecutive frames (at 60 fps) so make sure you do not have frameskipping enabled as it will surely break this effect. Other libretro-specific hacks like CPU overclock or run-ahead might also cause such issue.

**Comment by Augusto7743** [comment]
Using default settings in vsync swap now the game run correct.
Thanks.

**Comment by ekeeke** [comment]
You should close your issue then, so that the pile of pending issue reports does not stack up with resolved/outdated issues.

**Comment by Augusto7743** [comment]
Right :)
