### ISSUE TITLE
Issue with Demons of Asteborg (RG-350)

### ISSUE THREAD

**Issue by Danniel79** [libretro/Genesis-Plus-GX#276]
Console RG350.Retroarch 1.9.14.(Dingux(not beta))I'm having trouble playing Demons of Asteborg. The game won't load at all. The last time the game was launched on build 1.9.8. But she did not save progress there.In builds later than 1.9.8, there were problems with horizontal scrolling, the game did not move to the left.Now it does not start at all.

**Comment by Danniel79** [comment]
Standalone Wii Genesis Plus GX works fine.

**Comment by ekeeke** [comment]
Support for Demons of Asteborg particularely huge ROM size (around 15MB) needs to be added for each platform case by case as not all of them have enough embedded RAM to hold the emulator + retroarch + ROM buffer(s).

This needs to be done in Makefile.libretro by adding `MAX_ROM_SIZE = 16777216` in the platform specific compilation part. 

Looking at https://github.com/libretro/Genesis-Plus-GX/blob/master/Makefile.libretro#L458 it does not seem to have been added for MIPS32 based console like GCW0, etc

**Comment by Danniel79** [comment]
Thanks for the answer. I hope somebody will add these corrections. I have no time to do this unfortunately. Your emulator is excellent, I use it for many years to Wii.

**Comment by Danniel79** [comment]
Thank you again.Now the issue is close by adding  **MAX_ROM_SIZE = 16777216** in  Makefile.libretro.I'm happy.Demons of Asteborg works fine on RG350 now.
