### ISSUE TITLE
Incompatible features - Blargg NTSC filter + Hide MS Borders (left)

### ISSUE THREAD

**Issue by Apaczer** [libretro/Genesis-Plus-GX#282]
"Hiding Master System Side Borders" feature doesn't seems to work in conjuction with "Blargg NTSC filter" option. Setting any core specific video filters will instantly reshow side border.

That being said the SMS plus GX is functioning properly under this two features set to ON

**Comment by ds22x** [comment]
Well, the combination worked, but it didn't shift the image enough when enabling the Blargg NTSC filter option.
Anyway, https://github.com/libretro/Genesis-Plus-GX/commit/81fce948ac57abfcb7b7d9487f08a0d0650f94f8 should fix it.

**Comment by Apaczer** [comment]
Ty, did the job. Global RetroArch's Blargg *.filt'er was also an option, however they had heavier inpact on performance over internal feature
