### ISSUE TITLE
Sonic & Knuckles + Sonic 1 gives the anti-cheat screen.

### ISSUE THREAD

**Issue by TomTurbine** [libretro/Genesis-Plus-GX#292]
Tried it with both Sonic with the lock-on option in the menu (With the required files in the system folder) as well as using a rom with them both integrated, both give the screen where it prevents the game from loading.

**Comment by ekeeke** [comment]
That is normal behavior: https://segaretro.org/Lock-On_Technology#Lock-On_with_Sonic_the_Hedgehog

**Comment by TomTurbine** [comment]
Then how exactly do you boot into "Sonic & Knuckles - Sonic 1"? Since there doesn't seem to be anyway to actually play it then.

I understand that that was normal behavior when the system thought you were trying to cheat, but actually using the option on the emulator to enable it to play or using the rom were they were both integrated to play should bypass that.

**Comment by ekeeke** [comment]
Yes, that is what is explained in the linked article: the only benefit of inserting Sonic 1 is to be able to access all the levels of the Sphere game. There is no such game as Sonic 1 & Knuckles.

**Comment by TomTurbine** [comment]
I wanted to play the game growing up and never got to, guess I was wanting to play something that never existed.
And when I saw people had Sonic 1 and Knuckles integrated, might actually get around to it, guess it was just for the sphere thing.

Oh well, thank you very much.
