### ISSUE TITLE
Recent x86_64 Windows builds of the Genesis Plus GX core from the libretro buildbot will cause the entire RetroArch frontend to crash whenever the emulated Mega Drive encounters a memory address error exception.

### ISSUE THREAD

**Issue by akemin-dayo** [libretro/Genesis-Plus-GX#299]
Recent x86_64 Windows builds of the Genesis Plus GX core **from the libretro buildbot** will cause the entire RetroArch frontend to crash whenever the emulated Mega Drive encounters a memory address error exception.

No meaningful output can be found in the logs.

Illegal instruction exceptions do not cause this crash.

This crash occurs with the default `retroarch.cfg`.

**Self-built x86_64 builds (using the MinGW toolchain) are not affected.**

The last pre-built version of this core from the libretro buildbot that does _not_ reproduce this behaviour corresponds to Git commit SHA-1 ad3b754d01428ad18d47c10724c61c6b4dacd382.

I am able to reproduce the crash on the next available pre-built version of this core from the libretro buildbot, which corresponds to Git commit SHA-1 70867ab1a4e87b69388ec18345293d028f96bbe2.

That being said, this issue does **not** appear to be caused by _any_ actual code change between Git commits ad3b754d01428ad18d47c10724c61c6b4dacd382...70867ab1a4e87b69388ec18345293d028f96bbe2, but rather appears to be the result of _some_ kind of change in the libretro buildbot's toolchain / build environment, since my own self-built binaries of the latest relevant commit (specifically 492b4c63c552b6115bee7ff1e04868cbcd691e9a) work perfectly as expected.

### Reproduced with…
* RetroArch 1.10.3 (x86_64), Windows 10 21H2 19044.1706 (x86_64)
    * I used the **pre-built** binaries that are available from the libretro buildbot.
        * ad3b754d01428ad18d47c10724c61c6b4dacd382 was taken from [RetroArch release 1.9.11's RetroArch_cores.7z](https://buildbot.libretro.com/stable/1.9.11/windows/x86_64/RetroArch_cores.7z).
        * 70867ab1a4e87b69388ec18345293d028f96bbe2 (the next available pre-built binary) was taken from [RetroArch release 1.9.12's RetroArch_cores.7z](https://buildbot.libretro.com/stable/1.9.12/windows/x86_64/RetroArch_cores.7z).

### Confirmed to be unaffected
* RetroArch 1.10.3 (x86_64), Windows 10 21H2 19044.1706 (x86_64)
    * I used my **own self-built binaries** of the latest relevant commit. (492b4c63c552b6115bee7ff1e04868cbcd691e9a as of this writing.)
* RetroArch 1.10.3 (i386), Windows 10 21H2 19044.1706 (x86_64, via WoW64)
    * I used the latest i386 nightly core from the libretro buildbot. (492b4c63c552b6115bee7ff1e04868cbcd691e9a as of this writing.)
* RetroArch 1.10.3 (arm64), macOS 12.3.1 21E258 Monterey (arm64e)
    * I used the latest arm64 nightly core from the libretro buildbot. (492b4c63c552b6115bee7ff1e04868cbcd691e9a as of this writing.)
* RetroArch 1.10.3 (x86_64), macOS 12.3.1 21E258 Monterey (arm64e, via Rosetta 2)
    * I used the latest x86_64 nightly core from the libretro buildbot. (492b4c63c552b6115bee7ff1e04868cbcd691e9a as of this writing.)

### Untested with…
* Every other platform and/or architecture not listed here.

## Reproducing
1. Load an x86_64 Windows Genesis Plus GX core from the libretro buildbot corresponding to Git commit SHA-1 ad3b754d01428ad18d47c10724c61c6b4dacd382.
2. Make sure that the 68K Address Error behaviour is enabled in the core settings (this is on by default).
3. Cause a memory address error exception to occur in the emulated Mega Drive.
4. Observe how RetroArch does not crash, and the emulated Mega Drive behaves as how real Mega Drive hardware would. For instance, in mainline Sonic games, the error handler will appear.
5. Load a newer x86_64 Windows Genesis Plus GX core from the libretro buildbot.
6. Repeat steps 2〜3 from above.

## ※ UPDATE: Mega Drive Memory Access Error Exception Tester
I quickly wrote an extremely barebones Mega Drive application that causes a 68000 memory address error exception and… does literally nothing else.

It should be helpful for the purposes of reproducing this crash. (Hanging at a black screen == good, instantly crashing RetroArch frontend == bad ;P)

Source: https://gist.github.com/akemin-dayo/38200da0c42f9aebe55bd521970c9361

Pre-compiled ROM binary: [MegaDriveMemoryAccessErrorExceptionTester.md](https://github.com/libretro/Genesis-Plus-GX/files/8706266/MegaDriveMemoryAccessErrorExceptionTester.md)

**Comment by LibretroAdmin** [comment]
Hopefully this will be a workaround for now -
https://github.com/libretro/Genesis-Plus-GX/commit/f9e2c57818ae3874f8ecd49cabd81de6d586c410

**Comment by ekeeke** [comment]
This commit only added address errors on Sega CD CPU side (they were already supported on Genedis side).

That issue report seems to indicate it crashes whenever there is an address error (including Genesis CPU side) so I am not sure removing that compiler define is enough ?

In any case, if this causes issue, address errors checks and exception processing can be disabled from core settings so it would be better to change the default setting value to off rather than removing a feature that works fine (apparrently, it works fine on win32) on other  platforms and leaving this open to investiguate the cause of the crash as it could hide some other regression or code weirdness.

**Comment by ekeeke** [comment]
For reference, 68000 cpu address error emulation uses setjmp/longjmp C functions: they are high chances this is what causes the crash so I would rather investiguate what coulf have caused this to not work in win64 builds.

**Comment by LibretroAdmin** [comment]
@akemin-dayo Try to bisect the issue. You apparently know how to reproduce the problem you're having, so you're in an ideal position to bisect it and find the guilty commit.

**Comment by akemin-dayo** [comment]
I'll try and set up a build environment when I have time — is there any documentation on build prerequisites / dependencies or anything? Can't seem to find anything in the repo's documentation.

**Comment by akemin-dayo** [comment]
So I just built my own copy of the core using commit 492b4c63c552b6115bee7ff1e04868cbcd691e9a (the latest commit before your workaround attempt above), and… it doesn't crash.

This confirms my suspicion that this isn't actually caused by any code changes in the commit history, but rather some kind of build environment / toolchain change in the libretro buildbot.

For reference, all I did was run `make -f Makefile.libretro` on a system with the MinGW toolchain installed (since apparently this project is _extremely_ easy to build, according to its use of [libretro-infrastructure/ci-templates/windows-x64-mingw.yml](https://git.libretro.com/libretro-infrastructure/ci-templates/-/blob/master/windows-x64-mingw.yml)).

I can provide the binary I built if it helps.

**Comment by jdgleaver** [comment]
This is probably (maybe...) due to the fact that Windows builds on the buildbot have ASLR enabled: https://www.msys2.org/news/#2021-01-31-aslr-enabled-by-default

This tends to expose hidden bugs in the code - e.g. it 'caused' crashes in the picodrive core (now resolved) https://github.com/libretro/picodrive/issues/184, and prevents the px68k core from working https://github.com/libretro/px68k-libretro/issues/150

@akemin-dayo Could you confirm that if you build locally with ASLR enabled, the core crashes?

**Comment by akemin-dayo** [comment]
My local build seems to already have ASLR (Dynamic Base) and High Entropy VA enabled, according to the DLL flags.

![image](https://user-images.githubusercontent.com/1980487/168802471-3fc00400-703f-40e2-ad11-217b887c8922.png)

The libretro buildbot's DLL also has the same flags.

**Comment by jdgleaver** [comment]
Oh! Well thanks for checking. That indeed makes the issue quite mysterious... :(

**Comment by akemin-dayo** [comment]
Hmn, that doesn't really explain why self-built binaries work fine, though.

If I compile it myself, it works fine. If I use the libretro buildbot's pre-built binaries, then it crashes.

Hence why my current running theory is that it might not even be an issue with the code, but rather something to do with the buildbot's environment.

**Comment by LibretroAdmin** [comment]
Reverted the commit for now since it did not resolve the issue.

Hopefully someone in this thread can debug this issue and figure out the root cause of the problem. @m4xw already speculated it could be undefined behavior.

**Comment by bslenul** [comment]
Just tried that test rom above and same behavior (Win10 too), crashes with buildbot core, works fine if built myself.

Unrelated I guess, but just in case: the buildbot core is surprisingly big, 7.2MB (already stripped) vs. 3.6MB when built myself and only 2.9MB after stripping.

**Comment by ekeeke** [comment]
>Hmn, that doesn't really explain why self-built binaries work fine, though

it could be explained by the fact that the implementation of setjmp/longjmp (assembly code), like other C libraries functions, depends on the versionof compiler and libraries being used to build the executable

**Comment by ekeeke** [comment]
Could be related to
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100402

**Comment by jdgleaver** [comment]
Thanks, that's a good catch.

I also keep forgetting: we don't use regular MinGW on the buildbot - we use MXE for cross compiling the Windows builds. And indeed, we are using gcc 10.3.0 which does not seem to have the fix reported in that bugzilla link.

This poses something of a problem, because that's the latest version of gcc 10 available with MXE. Looks like we will need to jump to gcc 11 or 12 - but from the MXE issues list, that seems like trouble as well...

I guess we need to spin up a new build container and for the time being apply it only to this core, and test the result. This will take a little time....

**Comment by realnc** [comment]
I updated the environment the buildbot uses (it's based on the MXE cross-compiler environment). Instead of GCC 10.3, it uses GCC 11.3. This is the build:

[genesis_plus_gx-w64.zip](https://github.com/libretro/Genesis-Plus-GX/files/8712780/genesis_plus_gx-w64.zip)

Does that one crash?

**Comment by akemin-dayo** [comment]
I can confirm that the above GCC 11.3 build does not crash!

**Comment by ekeeke** [comment]
Maybe it's related to the version of libc being packed, rather than gcc executable itself.

**Comment by realnc** [comment]
> Maybe it's related to the version of libc being packed, rather than gcc executable itself.

libc is not actually being packed. The toolchain uses the libc that's provided by your Windows installation.

**Comment by akemin-dayo** [comment]
I just tested the most recent build from the buildbot (corresponding to 6923673821c227c24df9b6112b9949105c842574, file SHA1 hash `efbf32fb7e2d0f71cb9ebc45e6158e3e6f05b604`), and it seems like the necessary toolchain changes were made to the buildbot to prevent the crash from occurring!

As such, I will be closing this issue — feel free to reopen it if needed.
