### ISSUE TITLE
Crash issue in Bizhawk's libretro frontend related to region switching

### ISSUE THREAD

**Issue by Sonia-7** [libretro/Genesis-Plus-GX#313]
Originally I reported this in Bizhawk's repo, then in upstream. I was sent here from there so this should be the right place now.

Basically, the problem is that if you edit "genesis_plus_gx_region_detect" inside the "libretro_core_options.h" file from the default "auto" to "ntsc-u", "pal" or "ntsc-j" and compile, the core starts crashing upon rebooting in Bizhawk.

You can see the upstream report here:
https://github.com/ekeeke/Genesis-Plus-GX/issues/475

And below for Bizhawk repo's (the last comment fully details what's causing the crash)
https://github.com/TASEmulators/BizHawk/issues/3482

The info in those threads should prove useful for the fix.

**Comment by Sonia-7** [comment]
Tested and it's working perfectly. Thanks!

**Comment by LibretroAdmin** [comment]
That's great to hear. I will merge it then.
