### ISSUE TITLE
Marko's Magic Football (Mega CD) Graphic Bug

### ISSUE THREAD

**Issue by KamiLordus** [libretro/Genesis-Plus-GX#318]
On one of the first screens (location map) there is a graphic error - the bottom of the screen.
Please fix it.

![Bez tytułu](https://user-images.githubusercontent.com/123302593/215456644-1fb76b3e-a99c-4b44-bb0f-340eec470f23.png)

**Comment by BooBerry** [comment]
Can confirm it happens in both `Marko's Magic Football (Europe) (En,Fr,De,Es)` and `Marko (USA) (Unl)`.

This actually might be an upstream Genesis Plus GX issue (though someone should test with the standalone Genesis Plus GX on a Wii or GameCube to verify) and you should probably report it here: https://github.com/ekeeke/Genesis-Plus-GX/issues

**Comment by hizzlekizzle** [comment]
Yes, testing the non-CD one in blastem-libretro would be good, too, to see if it does it there, as well.

**Comment by BooBerry** [comment]
I can confirm it doesn't happen in either game on original hardware with both the MegaSD and Mega Everdrive Pro.

**Comment by KamiLordus** [comment]
@BooBerry Thanks for the advice. I also sent there.

@hizzlekizzle I checked the version on Sega Genesis (Marko) using Genesis Plus GX and there is no error there.

**Comment by BooBerry** [comment]
No, I saw it in both CD versions, the European and the US.

**Comment by KamiLordus** [comment]
Also checked both cd versions. Europe and US versions have the same problem.

**Comment by ekeeke** [comment]
This issue was already reported here https://github.com/libretro/Genesis-Plus-GX/issues/33 

I know what cause this (sub-cpu should be halted if it accesses word-ram when it is allocated to main-cpu) but postponed the fix as it involves some important code changes.

I guess you should close both in this repository since it is now traced in upstream repository.

**Comment by KamiLordus** [comment]
Sorry for the duplicate. I haven't reviewed all open tickets.

**Comment by ekeeke** [comment]
I fixed this in my repository, see https://github.com/ekeeke/Genesis-Plus-GX/commit/6cc8bbc2776dfbe62411fc1e8fbc5807c8e3558d

**Comment by KamiLordus** [comment]
Very good news. I hope I can test it soon :)

**Comment by KamiLordus** [comment]
Tested and works without any problems.
@ekeeke thanks a lot for fixing it.
