### ISSUE TITLE
Request: Overclocking more than 200%

### ISSUE THREAD

**Issue by ivan89el** [libretro/Genesis-Plus-GX#322]
For some games, 200% is not enough to be smoother (Road Rash series). It would be nice to have an additional 400-800%. Sorry for my English

**Comment by ds22x** [comment]
Added via https://github.com/libretro/Genesis-Plus-GX/commit/5f521bd186b0661f02f9f8f5ca6cf3862cb0d43e

**Comment by ivan89el** [comment]
Good job!
