### ISSUE TITLE
SG-1000 extended RAM no longer exposed

### ISSUE THREAD

**Issue by Jamiras** [libretro/Genesis-Plus-GX#323]
https://github.com/libretro/Genesis-Plus-GX/commit/6ec9ac2729b6bd4b67b61e3c5ccd4683ef6d995f#diff-0033c4d206c0f5ecb21459b1c42f39055aacfc7468b9729527c5dd94489c58aaR3432-R3433 caused `retro_get_memory_size` to only return 0x2000 for Knightmare (which I assume maps to `SYSTEM_SGII_RAM_EXT`). The memory needed by RetroAchievements starts at $2000, so the set no longer works in Genesis-Plus-GX.

If I pretend that `retro_get_memory_size` returns the old value of 0x10000, then everything works as expected. It appears that internally the expansion RAM is still 0x2000 bytes into `work_ram`. It seems like the easy fix would be to return 0x4000 (or more) for `SYSTEM_SGII_RAM_EXT` to restore the old behavior, but it could also be addressed by implementing the appropriate case in `set_memory_maps`.

**Comment by ekeeke** [comment]
Looks more like an error in RetroAchizvement for this game. 
SG-1000 available RAM size is either 1KB (original SG-1000 hardware), 2KB (SG-1000 II clone hardware) or 8KB (SG-1000 with RAM extension cartridge, mostly needed by MSX ports).

0x10000 corresponds to 64KB which is only available on Mega Drive.

**Comment by Jamiras** [comment]
If it's a RetroAchievements problem, it's because the data was exposed incorrectly. The set was designed around the way the memory was exposed and now it's not exposed that way any more.

Bottom line: This is what we're looking for (captured with my modifications to pretend more memory is exposed):

![image](https://user-images.githubusercontent.com/32680403/221303183-13df30e3-aade-450d-9c6e-55d4c39b0d5e.png)

The important thing to note is that this data is still there, it's just not exposed because `retro_get_memory_size` is returning a different value.

When the core says only 0x2000 bytes are exposed we treat the addresses as invalid (same memory without my modifications):

![image](https://user-images.githubusercontent.com/32680403/221303363-949a1b79-c33c-4c20-aa92-80d06c52e03e.png)

As a result, any of the achievements watching the blue addresses (there are more offscreen too) won't work.

If there is supposed to be mirroring, it's not working. This is what I see at $0000 for the same frame:

![image](https://user-images.githubusercontent.com/32680403/221303505-212c97e7-d07e-4bce-b612-d27a5dc581ce.png)

I'm not arguing that the basic system needs to expose more than 0x2000. This problem seems to be limited to Knightmare and Rally-X (at least those are the only titles players have reported issues with). Both of them are expecting to find data above $2000, but the core is telling us it doesn't exist.

**Comment by ekeeke** [comment]
As explained above, it was a mistake in initial libretro port (SG-1000 hardware was ignored do it was treated as default case, which corresponded to Mega Drive RAM size)

Reverting to incorrect size would be incorrect. The correct solution is to either fix RAM offsets for SG-1000 games to use correct RAM offsets or to fix Retroachievement plugin so that reading a RAM address above the available RAM size would not result in an error but will result in RAM address being correctly masked according to RAM size (so accessing RAM offset 0x2000 would actually access RAM offset 0x0000, just like real CPU would)

**Comment by ekeeke** [comment]
Wait. I think I understand better the issue. Those games actually use a different RAM extendion cartridge,   which maps 8KB RAM between 0x2000 and 0x4000 (where there is ROM mapped usually)

See 
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/cart_hw/sms_cart.c#L162
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/cart_hw/sms_cart.c#L942

So yes, the proper solution seems to expose proper RAM mapping for these games ( the RAM size is 8KB but it does not start at address 0x0000).

**Comment by ekeeke** [comment]
I pushed a commit in upstream repository which should fix the available system RAM size for these games
https://github.com/ekeeke/Genesis-Plus-GX/commit/cc60ba57bf869d2b8526ea6e9882064acd53ba1d

**Comment by ds22x** [comment]
Implemented via https://github.com/libretro/Genesis-Plus-GX/commit/ff371e24cd8ce85dfdad41f66726af663c2cc801

**Comment by Jamiras** [comment]
Confirmed the additional memory is exposed for Knightmare. Thanks for the fix.
