### ISSUE TITLE
Marko/Marko's Magic Football Sega CD (Mega CD) Possible Graphic Corruption

### ISSUE THREAD

**Issue by davidj1987** [libretro/Genesis-Plus-GX#33]
I tried both the US and EU version since I believe the US version was unlicensed release and it may have been a quick and dirty region change and I have no idea about converting PAL Mega CD games. When you are about to start a level there is some graphic corruption near the bottom of the screen. I did not see this in the Genesis version.

I believe this happens on other emulators too. Now I don't think this longplay was done on Genesis Plus GX but at 2:24 if you pause it, this shows what I am talking about:

https://www.youtube.com/watch?v=ehE9eO4_l5Y

**Comment by ekeeke** [comment]
I would need confirmation this does not happen on a real Mega CD as well, especially when the same thing occurs in every other Sega CD emulators (Fusion, Picodrive, Gens).

**Comment by ekeeke** [comment]
Does not happen on this real hardware video so it's likely an emulation bug.

https://www.youtube.com/watch?v=zc4TR4zx7WQ

**Comment by ekeeke** [comment]
Strangely, that bug seems caused by Sub-CPU trying to access Sega CD Word RAM after it was returned to Main-CPU side, which is clearly not something software is normally allowed to do.

**Comment by LibretroAdmin** [comment]
Upstream tracks this now
