### ISSUE TITLE
Sonic & Knuckles Lock On

### ISSUE THREAD

**Issue by KoyMcCloud** [libretro/Genesis-Plus-GX#335]
The Sonic and Knuckles Lockon function no longer works, any time I try to boot up Sonic 3 with the S&K Lock On activated, it simply starts as Sonic and Knuckles. I downloaded an earlier version of the core, and the lock on function works fine.

**Comment by bslenul** [comment]
Bisected, it started to happen with 4bb149ba0b798294fbfc51de31a97af08c018542
