### ISSUE TITLE
"Address Error" option not reflected on the Mega CD Sub CPU

### ISSUE THREAD

**Issue by OrionNavattan** [libretro/Genesis-Plus-GX#337]
Testing my [experimental error handler](https://github.com/OrionNavattan/MegaCDErrorHandler) revealed that the option for enabling/disabling address errors isn't reflected on the Mega CD Sub CPU. The test ROM in the above repository labeled "Mode 1 Error Handler Test (Sub Addr).bin" is programmed to trigger an address error on the sub CPU, but instead the sub CPU continues as if nothing happened (the green screen it ends on is NOT correct behavior). This issue does not occur in the OpenEmu version of GPGX, so I suspect it is an issue specific to the libretro core.

**Comment by ds22x** [comment]
Pulled the relevant commit.

**Comment by OrionNavattan** [comment]
The latest commit has NOT resolved this issue. The bug described above is still occurring.

**Comment by ds22x** [comment]
![MCD Error Handler Test (Sub Illegal)-230828-131832](https://github.com/libretro/Genesis-Plus-GX/assets/45218067/07f33fa7-2760-4af6-8918-7eda0a12721b)
Is what I get with the latest core from the buildbot.

**Comment by OrionNavattan** [comment]
In retrospect, I should have provided a copy of a ROM that actually triggers the issue.
[MCD Error Handler Test (Sub Addr).zip](https://github.com/libretro/Genesis-Plus-GX/files/12459423/MCD.Error.Handler.Test.Sub.Addr.zip)

**Comment by ds22x** [comment]
![MCD Error Handler Test (Sub Addr)-230829-113305](https://github.com/libretro/Genesis-Plus-GX/assets/45218067/e795a7a5-3163-4632-bce0-9d4994d01c10)
Is what I get on a Windows 11 setup.
Trying it on Android, I do get a green screen, so it might be platform related.

**Comment by OrionNavattan** [comment]
In that case, it is a platform-specific bug. The current build of the core on macOS Metal has the same behavior as Android.

**Comment by ds22x** [comment]
Just checked both up- and downstream Makefile.libretro files, and it's only explicitly set for Windows in either of them.

**Comment by ekeeke** [comment]
Yes, I disabled it in standalone gamecube/wiiport as address error emulation can have a significant impact on emulation performance and no Mega-CD game or demos rely on it anyway.

I think I enabled it in libretro makefile for windows only for same reason but you are free to add it in other platgorms where peformance is not sensible.

**Comment by ds22x** [comment]
I'd figure those platforms would realistically be OS X, and Unix platforms that are not specifically defined in the Makefile?
