### ISSUE TITLE
genesis_plus_gx_add_on bad default value

### ISSUE THREAD

**Issue by rtomasa** [libretro/Genesis-Plus-GX#341]
I've noticed that `genesis_plus_gx_add_on` is setting `disabled` as default value, but this value is not one of the 4 available ones. This is leading to unexpected behaviours and errors on libretro based frontends.

**Comment by ds22x** [comment]
Fixed by https://github.com/ekeeke/Genesis-Plus-GX/pull/536, closing.

**Comment by ds22x** [comment]
Upstream also reports [1
7.4](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/libretro/libretro.c#L2837) for the Libretro core.
If it isn't intentional, it's better to report it at https://github.com/ekeeke/Genesis-Plus-GX/issues so upstream can benefit from it as well.

**Comment by KamiLordus** [comment]
Ok thanks for the clarification.
