### ISSUE TITLE
[Regression][SegaCD][Android] Emulation freezes when playing SegaCD FMV

### ISSUE THREAD

**Issue by jmaneyrol69** [libretro/Genesis-Plus-GX#342]
## Description

I recently updated to the latest Genesis Plus GX libretro core build and since then, any SegaCD games that uses FMV I've tried freezes the emulator when playing FMVs. The freeze happens randomly: sometimes right at the beginning of a video, sometimes after a coupe of seconds.

## Environment

- Retroid Pocket 3+
- Android 11
- Core build: v1.7.4 7aba063
- Video: tested with gl and vulkan
- Architecture: reproduced both with 32bit (arm7) and 64bit (arm-v8)

## Games tested

- Dracula Unleashed (USA)
- Jurassic Park (USA)
- The Terminator (USA)
- Eternal Champions (USA)

**Comment by ekeeke** [comment]
There was indeed a regression introduced by https://github.com/ekeeke/Genesis-Plus-GX/commit/da8e4e547affcbd295d2e3028735b3283ec2c462 which would cause many games to hang when doing CDC DMA.

It has been corrected by https://github.com/ekeeke/Genesis-Plus-GX/commit/3397941b609cef77086c3225121396e74ce444c2 which now have been backported into this repository so updating to latest Retroarch build should fix these issues

**Comment by jmaneyrol69** [comment]
Yes, it's working now! Many thanks @ekeeke!
