### ISSUE TITLE
Alice Sisters - buzzing sound, no music

### ISSUE THREAD

**Issue by oncemailtime** [libretro/Genesis-Plus-GX#345]
Start the game, watch the intro, and stage 1 has this constant buzzing. But if you skip the intro, then music and sfx work normally.

Using libretro nightly build. Haven't tested earlier builds.

**Comment by ekeeke** [comment]
Tested the game on real hardware (PAL MD1 VA4 switched to 60Hz) and the music also crashes when stage 1 starts (no buzzing though, just silence) if you leave the intro running after power-on so this seems to be more a bug in the game.

Note that it does not occur after a soft reset if you skipped the intro at first boot (and got music playing normally once) so it might be related to some data being not correctly initialized or resetted during intro.
