### ISSUE TITLE
[Feature Request] "VDP mode" core option (for MD PAL ASIA / MegaKey behavior)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [libretro/Genesis-Plus-GX#349]
Hello, libretro-devs!
Can you add "VDP mode" core option please, like ekeeke implemented in the Wii/Gamecube port? 
Description is here: https://github.com/ekeeke/Genesis-Plus-GX/issues/558

I guess the core options must look something like this: [Auto / NTSC / PAL]

https://github.com/ekeeke/Genesis-Plus-GX/blob/master/gx/config.c
- Auto = ("config.vdp_mode = 0")  is  default value
- NTSC = ("config.vdp_mode = 1")
- PAL = ("config.vdp_mode = 2")

**Comment by ds22x** [comment]
Added via https://github.com/libretro/Genesis-Plus-GX/commit/ba9fc37cfa4930311a9c77b1d8a23df0cae95e9a

**Comment by eugene-s-nesdev** [comment]
Thank you very much!

**Comment by eugene-s-nesdev** [comment]
@ds22x, Can you merge/pull this fix (https://github.com/libretro/Genesis-Plus-GX/commit/ba9fc37cfa4930311a9c77b1d8a23df0cae95e9a) to the ekeeke's upstream libretro branch (https://github.com/ekeeke/Genesis-Plus-GX/tree/master/libretro) please?
