### ISSUE TITLE
Mega Man Wily Wars Mottzilla Patch SRAM Not Working

### ISSUE THREAD

**Issue by Awakened0** [libretro/Genesis-Plus-GX#37]
It seems saving with this patch is broken in the latest core. I tested it and after beating a boss and saving, when you quit and load the game again the boss isn't faded out. There's someone else who noticed it first here: http://libretro.com/forums/showthread.php?t=5026

The original issue report: https://bitbucket.org/eke/genesis-plus-gx/issues/200/mega-man-the-wily-wars

**Comment by ekeeke** [comment]
Please close this and re-open in my repository.

**Comment by twinaphex** [comment]
Closing this as per ekeeke's request
