### ISSUE TITLE
Overclock Option?

### ISSUE THREAD

**Issue by blackman91** [libretro/Genesis-Plus-GX#38]
Do you plan on adding this option to correct the slow down in games like Sonic and Megaman the wily wars? I think Regen has this option but it is windows only.

**Comment by blackman91** [comment]
I was informed there is a patch to add this option but eke eke does not want to add it, wonder why?

**Comment by hizzlekizzle** [comment]
I don't want to speak for him but I believe he's focused on making genplusgx as accurate as possible and adding this wouldn't serve that goal. There are hardware mods to overclock a genesis IRL but in the same vein, byuu isn't going to add SuperFX overclocking to bsnes/higan even though such a thing can be done on a physical cart/system.

**Comment by blackman91** [comment]
It could be added as a turned off option by default though, I don't see how just adding that would hurt emulation accuracy in general and a few games would benefit greatly from it. Also some snes emulators like snes9x do support overclock, do not know how accurate they are though.

**Comment by ekeeke** [comment]
I've never been submitted any patches, only user requests.

Adding optional 68k overclocking is very trivial though, only a few lines changes in m68kcpu.c to turn the clock multiplier (MUL) which is actually fixed to 7 into a configurable parameter, but I won't do it personally because it would make the 68k emulation code quite unoptimized and slower for very little benefits (only a few games would support it).

Nothing prevents anyone to do it himself if he wants, I really don't care, just don't bug me if it becomes unstable or breaks other things.

Btw, you can correct the speed of Willy Wars by simply switching the region to USA once the game is started - or use a patch / cheat code to force the region code to "U" in ROM header.

**Comment by hizzlekizzle** [comment]
Ok, if you're amenable to it, I'll see about getting a PR together soon.

**Comment by blackman91** [comment]
But changing the region to USA fixes the lag in some battles against the robot masters like when geminiman uses the gemini laser?

**Comment by blackman91** [comment]
Changing the region and resuming the game always gives me this screen:
http://i1312.photobucket.com/albums/t539/talos910/Screenshot_2016-02-06-22-04-01_zpsot1oww9q.png

Someone knows what I am doing wrong?

**Comment by ekeeke** [comment]
Nothing, I was wrong actually, the libretro port forces a reset when region is changed so it's not possible to bypass the region check this way.

**Comment by blackman91** [comment]
Thanks any plans on adding a way to bypass the region check? It seems in the patched version of wily wars the srm is not working.

**Comment by ekeeke** [comment]
Saving with the SRAM-patched hack has been fixed by latest commit in my repository, but this has not yet been synced in libretro repository.

**Comment by blackman91** [comment]
Seems the retroarch core still lacks the fix for Wily wars.

**Comment by Awakened0** [comment]
It's in there now. I tested it and it loaded an old save with some robot masters I defeated grayed out.

**Comment by blackman91** [comment]
Yeah it is working now, thanks a lot guys, great job as always.

**Comment by retrobenny** [comment]
Such a shame to not allow an overclock option,I have seen what overclocking can do in Megasis running that S1 hack called Sonic 1 Multi where all objects spawn endless clones and normally slows everything to a crawl for obvious reasons,but with it overclocked,it was still fast with a massive amount of jumping fish badniks on the screen.

**Comment by ekeeke** [comment]
It has nothing to do with accuracy, Genesis Plus GX is more accurate than Regen, yet it does not have all features Regen has, while having features other emulators don't have. It's all about choice really, devs have choice to do whatever they think is best for their emu and you have choice to use whatever emu you want.

Now, I clearly explained the technical reasons why I didn't want to add CPU overclocking and I also explained how it could be done so anyone could do it and share his fork if they really want it. Shame is on you, not me, for not getting it or not wanting to accept it, really.

**Comment by retrobenny** [comment]
What game was it that could only be ran on the Wii version of Genesis Plus GX?
It wasn't the Ultimate Mortal Kombat 3 game with 10MB,it was some other game I can't remember the name of that could only be ran on that specific Wii version of the emulator and nothing else.
Can that one be ran on the RetroArch core for Android now?

**Comment by ekeeke** [comment]
I absolutely have no idea what you are talking about or how it is related to the former discussion but the compatibility is tied to the core so it's the same for all ports providing they are using the same core version, the Wii port makes no exception.

**Comment by blackman91** [comment]
"I've never seen any patches being submitted, only user requests"
Well hunterk from retroarch said he has a patch and told you about it: http://libretro.com/forums/showthread.php?t=1455&page=2&p=35942#post35942

**Comment by ekeeke** [comment]
The only discussion about this was in googlecode issues, now copied back here: https://bitbucket.org/eke/genesis-plus-gx/issues/223/overclock-cpu-for-games

Maybe that what that guy is referring to when saying I am not interested to do "it" but I again, I don't remember having discussed anything with that guy or received any patch from him.

Anyway, as explained in previous posts, I don't need a patch.

**Comment by blackman91** [comment]
So has anyone tried to add the overclock option to the core?

**Comment by blackman91** [comment]
Now with the new bounty system can this be added?

**Comment by blackman91** [comment]
Could someone add a bounty for this feature? I am willing to donate.

**Comment by retrobenny** [comment]
Having it for this would allow Toy Story's DOOM Engine run at a fluid 60fps which looks amazing.
This instance requires extreme overclocking,and the conventional use for Sonic game lagging requires much less overclocking but makes them more enjoyable to have a nonstop full speed experience.

I wouldn't mind seeing the proper kind of overclocking for any of the SNES emulators out there too.
Earthbound's slowdown when in Moonside and some other areas is the easiest example I can think of for SNES games.

**Comment by saftle** [comment]
@blackman91 anyone can create a bounty. Just go to bountysource.com, sign up and you can manually search for this issue from bountysource and apply a bounty to it.

**Comment by bkoropoff** [comment]
Give https://github.com/libretro/Genesis-Plus-GX/pull/105 a try if you want to play with overclocking.

**Comment by ekeeke** [comment]
This should be closed now that is has been implemented and merged.

**Comment by blackman91** [comment]
For some reason the android core still doesn't have the overclock option.

**Comment by ekeeke** [comment]
Needs to be enabled in Android.mk, same as CHD support and Sprite Limits removal

**Comment by blackman91** [comment]
The remove sprite limit option option is already there I think.
