### ISSUE TITLE
[Issue/Request] Soft Resetting

### ISSUE THREAD

**Issue by bleakassassin** [libretro/Genesis-Plus-GX#39]
Just as the title suggests: games act as if you've turned the system off then back on if you reset using this core in RetroArch instead of pushing the reset button. Without it, games like X-Men become impossible to beat as intended. Other games that remember settings such as control configurations or enabled cheats on a soft reset forget these, too.

At first I thought this was a RetroArch issue, as the response in my now-closed issue states. But then I noticed that soft resetting works just fine with NES games like Rad Racer and IronSword. Maybe the potential to use the functionality wasn't there awhile ago, but it appears to be there now.

**Comment by ekeeke** [comment]
AFAIK, it's not possible to distinguish between soft and hard reset in libretro API, there is only one retro_reset function so it's either one or the other. As mentionned in the other issue about Sega CD BIOS, libretro port of Genesis Plux does a hard reset by default. 
It's only one line change in libretro.c to switch that though.

**Comment by bleakassassin** [comment]
If I'm getting what you're saying correctly, you _can_ soft reset in the Libretro system. It's just that you only get either that or a hard reset, not both. Is that correct?

I'd think that having the reset option be a soft reset would be a better option, then. Many games make use of soft resetting, so they'd be missing some sort of functionality without it. Closing a game and restarting it, or switching to a different game and back, should effectively do the same thing as a hard reset anyways considering that that's what a hard reset is meant to simulate. Are there instances where a hard reset would be preferable if you want to keep playing the game right away? I honestly can't think of any.

**Comment by ekeeke** [comment]
Correct, unless I'm missing something undocumented in libretro API off course.

I agree having the reset option acting as the emulated console reset button makes more sense, this is how I've implemented it in the Wii version but I don't remember why it was initially done like that in the libretro port.

There are some cases where a hard reset could be needed (for example if you hit a bug in game which halts the system entirely and requires to restart the whole console hardware, not just CPU) but in this case, reloading the game indeed does a system power off/on by default.

As said above, this is a very simple fix so if you want it done quicker, I'd suggest you clone this repository, patch it yourself then submit a pull request.

You only need to change this line in https://github.com/libretro/Genesis-Plus-GX/blob/master/libretro/libretro.c

`void retro_reset(void) { system_reset(); }`

by

`void retro_reset(void) { gen_reset(0); }`

**Comment by bleakassassin** [comment]
Huh, I didn't think about system crashing. The only system crash I know of that I can consistently perform is one in Sonic the Hedgehog (MD, of course), and I was able to soft reset just fine after switching that bit of code. I guess there could be more severe crashes in other games that could impact that, but I'm not aware of any myself.

I've never attempted to commit anything to any project on GitHub until now. The forking, editing, submitting pull requests... this is all new to me. This has been a bit of a learning experience for me, so I hope all involved don't go too harshly on anything I did wrong. Even if you did all of the "figuring out" for this change, it feels nice for me to directly help in any way!

**Comment by bleakassassin** [comment]
Looks like you're going to have to do this yourself, after all. My pull request got passed up. And without a single comment as to why.

That's the last time I ever try to directly help with something related to RetroArch. You extend a hand to aid, but you only get swatted down instead.

**Comment by twinaphex** [comment]
Two days waiting for a comment means being 'swatted down'?  I had no idea what this pull request was intending to accomplish, so I was waiting on somebody knowledgeable to comment instead on it before we merge something that @ekeeke would not be pleased with. That is it, basically.

Please don't manufacture fake controversy now where there is none. It's very tiring doing your best to really try to be nice to everybody and still people paint you in the end as if you are some demon. No comment received in two days instead of it being directly merged simply means == 'I don't know what to do with, requesting comment from others more knowledgeable than me' on it before I merge something that would not be welcome to upstream.

**Comment by bleakassassin** [comment]
Ah, just as I was about to edit my comment.

I wasn't going to perceive it as "passed up" until I saw a later PR get merged over mine. I should have considered the extent of what was being suggested until that, though. Code edits and the implications of them do need to be taken into consideration.

I have much more that I'd like to say, but it wouldn't be directly related to development in any way. Here, I'll just say that my intent with that post is not to stir controversy so much as it is (now was) a personal statement. But I can see why it would appear otherwise.

**Comment by twinaphex** [comment]
I had no idea what to do with your pull request, that is why I was waiting on others to comment on it. Normally I just auto merge everything if I dont' see anything wrong with it, but I'm afraid to do that with repositories where we are a shallow fork since we want the upstream author to have as much control as possible over the repo. 

Honestly, you guys are painting me into a corner here where I'm damned if I do, damned if I don't. Authors from other projects complain about us not being upstream friendly, then when I try and do that, you get blasted over that too.

So from now on, you send these pull requests directly to ekeeke's upstream repo instead. Then I'll just pull from that instead whenever stuff is updated.

But, seriously, STOP assuming that I am out here to 'swat you down' or 'turn you down'. That gets really annoying especially when I don't even know you and have never treated you wrong.

**Comment by bleakassassin** [comment]
**[Bolded parts are relevant to this submitted issue or development.]**

**Let me clarify: My previous post was meant to be a full retraction of my knee-jerk reaction.** But it seems apt enough to say a bit of my piece. It'd probably help explain my composure on the internet.

I'm probably the most emotionally-driven person I know. So much so to an immense fault. It really does adversely affect me. Ironic considering that I also like technology and technology developments, which exist in a world where emotion must be hidden or put aside for cold hard facts. That's something I tend to forget. Particularly in the worst possible moments. But that's who I am. It helps in other places in life, and I'd never want to change that.

I've seen enough of your posts elsewhere to know that I'd probably be the last person you'd ever want to talk to in real life. I'm saying nothing bad about you, just that we seem to be as close to polar opposites as people can get. **Regardless of any of that, I wish to help in ways that I realistically can. I believe in the Libretro project and that it will lead to great things and that a immense number of people will look into it as time passes on. That's why I went through the effort to learn how to do all that stuff on GitHub.** I can only hope that any future communications are civil. That's probably the best I can ask for.

**Anyways, I hope that you do put an appropriate amount of consideration into that pull request,** regardless of who made it.

**Comment by twinaphex** [comment]
>I've seen enough of your posts elsewhere to know that I'd probably be the last person you'd ever want to talk to in real life.

I think people should stop making assumptions about my character based on random stuff they see here or there on the Internet. Newsflash: it's the Internet, and a lot of bullshit and smear and character assassination get posted. And I still try to put up with it, put up a brave face and not let it affect me much. 

Anyway, forget about the whole thing. If this is something you and ekeeke think should be done (and it looks like it from this discussion), I'll just merge it. But I don't like it when people don't voice their grievances first before then making some kind of grandiose exit and saying in leaving how badly treated they were when literally nothing happened and all it does is unfairly smear me and the project as if I am some kind of non-cooperative guy that doesn't want to get along with people, which couldn't be furthest form the truth.

**Comment by bleakassassin** [comment]
I stated directly in my message that I'm not saying anything bad about you. I also didn't say anything other than what I directly stated. The non-cooperative part you stated is you putting words in my mouth. I can see why anyone might think that given my knee-jerk reaction, but whatever.

I agree with the unnecessary text. I'll repeat the last part of my previous message: 

**I don't know if it'd be appropriate or advised, but I'd be fine with removing all messages after the one where I stated that I made the pull request. I don't want to crowd up any more of GitHub with non-development text than I already have.**

**Comment by twinaphex** [comment]
Alright, if that is your request, we'll do that.

**Comment by bleakassassin** [comment]
The PR was merged. There's a lot of growing pains for me when it comes to new things like this. At least the change was made.

Oh, and I'm sorry for any distress/annoyance I might or might not have caused you, @ekeeke. Anyone, really.

**Comment by twinaphex** [comment]
No problem, we'll forget about this occasion.
