### ISSUE TITLE
Using Rewind in SG-1000 Games Corrupts Graphics

### ISSUE THREAD

**Issue by bleakassassin** [libretro/Genesis-Plus-GX#43]
Just as the title states. When you use RetroArch's rewind feature, all graphics on-screen for these games become corrupted. Any graphics that get refreshed or updated afterwards appear normal.

This issue applies only to SG-1000 games. Games for the Master System and later don't have any issues with rewinding. I'm guessing that this will be low priority given the affected system being emulated, which is completely understandable.

I hope this doesn't come off as me bombarding the Libretro project with issues. I just wanted to bring this up before I forgot about it.

**Comment by ekeeke** [comment]
I just checked and there seems to be an issue with savestates on SG-1000 (which explain why rewind would not work). I will try to figure out what caused this to happen, I know it used to work before but it's not tested a lot so...

**Comment by ekeeke** [comment]
@bleakassassin : please close this as this is a core issue and reopen in https://github.com/ekeeke/Genesis-Plus-GX/issues so I can more easily keep track of it.
