### ISSUE TITLE
Genesis BIOS (bios_MD.bin) doesn't work

### ISSUE THREAD

**Issue by SigmaVirus** [libretro/Genesis-Plus-GX#44]
According to this issue here:
https://github.com/ekeeke/Genesis-Plus-GX/issues/42

and this commit here:
https://github.com/ekeeke/Genesis-Plus-GX/commit/9310dcf92c958f5e5f2a04c17b2118565ee38640

this BIOS file should be working: **bios_MD.bin**

My bios_MD.bin file have the following checksums:

CRC32: 	5F5E64EB
MD5: 	45E298905A08F9CFB38FD504CD6DBC84
SHA-1: 	453FCA4E1DB6FAE4A10657C4451BCCBB71955628

and the size for this file is 16384 (16 KB)

I placed it in the system folder under my Retroarch folder as instructed but nothing shows up when I start my game (Castlevania Bloodlines) and it goes straight to the game without showing the TMSS screen.

This BIOS file is working correctly in Kega Fusion 3.64 so I thought it would work here too.

I'm trying to move away from Kega Fusion and use as much Libretro cores as possible because of how easy things are to maintain and I really would like this to work.

What could be the problem here?

Everything is up to date both core and Retroarch wise using latest nightly builds.

Thanks in advance!

**Comment by hizzlekizzle** [comment]
Works here. Did you enable the 'system bootrom' core option first?

**Comment by fr500** [comment]
Is your system directory configured?
chck under directories/system

**Comment by SigmaVirus** [comment]
@hizzlekizzle , @fr500 

It's odd, I don't seem to have a 'System Bootrom' core option at all.

The funny thing is I know my system folder works because my Bsnes chips (cx4 and dsp1b) and my GBA BIOS used for mGBA is working perfectly.

What's the checksum on your bios_MD.bin guys? Does it match mine or is it different?

**Comment by hizzlekizzle** [comment]
The checksum on my BIOS matches yours.

System bootrom core option should definitely be there (just verified on a nightly build of the core). It's the 4th option from the top:
![system-bootrom](https://cloud.githubusercontent.com/assets/2805586/13397601/48940218-dec0-11e5-9957-a988d64d3029.png)

**Comment by SigmaVirus** [comment]
OK, my core settings screen does not look like that and I only have 3 options to choose from when loaded:

HW Shared Context Enable
Dummy On Core Shutdown
Autimatically start a core

However under my Retroarch folder I have a config file named retroarch-core-options.cfg and if I open it in Notepad, there is a line called **genesis_plus_gx_bios** which had the value of disabled.

It does not make a difference if I change it from disabled to enabled, still no TMSS screen.

I would like to point out though that dragging the bios_MD.bin to the Retroarch.exe opens up/load the TMSS screen actually, so at least I know it's good.

It's not life or death critical to be able to see the TMSS screen but it's annoying that I can't get it to work despite having the genesis_plus_gx_bios option set to enabled.
It should just work.

**Comment by hizzlekizzle** [comment]
Ah, you're looking in settings > core, the core options we're referring to are in quick menu > core options. Load up some content, go back into the menu and then use the 'core options' menu there. Once you enable the option, close content from the quick menu and then load up another Genesis game (that is, 'restart content' may not be enough to activate it) and it should start working.

**Comment by SigmaVirus** [comment]
OK, so I managed to get to that core options menu that you showed me and the option I was looking for was already enabled.

The reason it was enabled is because I modified the retroarch-core-options.cfg earlier today and it doesn't matter how many times I switch that option between disabled/enabled, it still doesn't work.

I have done what you have told me @hizzlekizzle and things are up to date.

The only way for me to see the TMSS screen is for me to drag the bios_MD.bin to Retroarch.exe, but that does nothing really regarding this issue.

Anything else I could try?

**Comment by hizzlekizzle** [comment]
Dunno, I'm stumped. It worked right away for me in Linux and for fr500, who uses Windows. I assume you're also on Windows since you mentioned Kega and Exodus.

if you run retroarch_debug from a command line with --menu --verbose does there should be a line that says:
[libretro INFO] :: Mega Drive TMSS BOOTROM is/should be located at: /path/to/system_dir/bios_MD.bin
If it says 'is', it's finding it and something else is wrong. If it says "should be" it's not finding it properly.

**Comment by SigmaVirus** [comment]
I got it to work finally, I had to go into directory settings and set the exact location to my system folder.

I find this odd because both my Bsnes chips/ROMs and my GBA BIOS worked straight away and they're also in the system folder.

Anyway, I guess I'll close this one now since there was nothing wrong.

Thanks for your help guys!

**Comment by SigmaVirus** [comment]
I'd like ask if it's possible to make the 'System bootrom' option enabled by default?
Is there any disadvantages for doing this?

**Comment by ekeeke** [comment]
There are actually several reasons why it would be a bad idea :

1) the original console model did not have any boot rom or licensing screen, only the later models 

2) several games (mostly unlicensed ones but also some early titles ) are not compatible with these later models 

3) this is an annoying licensing screen that the majority of people would prefer not to endure

4) it forces people to download and use an additional rom file which has no real use for emulation and no effect on how the game is playing

I return you the question: what would be the advantages of having an optionnal feature that the majority of people are not going to use enabled by default?

**Comment by SigmaVirus** [comment]
@ekeeke 

Thanks for your thorough explanation, I was just curious in whether or not there would be any disadvantages for enabling it by default and you certainly answered my question to the fullest and then some.

To answer your counter question, I guess there is no advantage for enabling it by default.
Again, I was just curious why it was disabled by default.
