### ISSUE TITLE
Playing zipped Sega CD games results in no music

### ISSUE THREAD

**Issue by saftle** [libretro/Genesis-Plus-GX#62]
When playing a zipped Sega CD game, it automatically only extracts the first ".bin" file from the zip, rather than the cue file and the additional tracks. This results in no audio, since the additional track bins nor the cue file are being extracted.

The other issue that I noticed, is that after quitting retroarch, the extracted bin file will still be on the drive, rather than being cleaned up. Is this intentional?

I am using the newest WIndows buildbot build via the Updater.

**Comment by saftle** [comment]
This actually might. be a Launchbox related issue, rather than an issue with the core or retroarch itself. I'll look into this more in the meantime.

**Comment by fr500** [comment]
our ZIP support only extracts the first file from the archive. It's a
RetroArch issue

**Comment by saftle** [comment]
Thank you @fr500. I found both issues. I'll link them here and close this. Thanks again.

https://github.com/libretro/RetroArch/issues/2614
https://github.com/libretro/RetroArch/issues/2878
