### ISSUE TITLE
Adding Support for Steam Link

### ISSUE THREAD

**Issue by retuxx** [libretro/Genesis-Plus-GX#66]
Do you think it is possible to add support for Steam Link devices? You can find the Steam Link sdk at: https://github.com/ValveSoftware/steamlink-sdk

**Comment by fr500** [comment]
RetroArch doesn't have a steam link target.
I guess you mean this for standalone Genesis Plus GX? then the correct repo is:

https://github.com/ekeeke/Genesis-Plus-GX

**Comment by retuxx** [comment]
Sorry my fault.
