### ISSUE TITLE
Mouse Cursor visible

### ISSUE THREAD

**Issue by CromlechDE** [libretro/Genesis-Plus-GX#72]
When I change Aspect Ratio to NTSC PAR or PAL PAR the mouse cursor is always visible. It doesn´t happen when it stays at AUTO.

Retroarch 1.4.1
Windows 7 64bit

**Comment by meepingsnesroms** [comment]
This is not a core issue, retroarch handles all i/o, please close and file it here.
https://github.com/libretro/RetroArch/issues
